services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Disable Spring Boot's internal docker-compose support when running inside Docker
      - SPRING_DOCKER_COMPOSE_ENABLED=false
      # Override the vector store host to point to the docker container name 'qdrant'
      - SPRING_AI_VECTORSTORE_QDRANT_HOST=qdrant
      - SPRING_AI_VECTORSTORE_QDRANT_PORT=6334
      # Pass the OpenAI API key from your host machine's environment to the container
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Database connection settings
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=spring_ai_db
      - DB_USER=root
      - DB_PASSWORD=root
      # OpenTelemetry Endpoint (switching to the HTTP port 4318)
      - SPRING_AI_OTEL_ENDPOINT=http://jaeger:4318/v1/traces
    networks:
      - spring-ai
    depends_on:
      - qdrant
      - mysql
      - prometheus
      - jaeger
      - grafana


  qdrant:
    image: 'qdrant/qdrant:latest'
    ports:
      - '6333:6333'
      - '6334:6334'
    networks:
      - spring-ai
  prometheus:
    image: 'prom/prometheus:v2.39.0'
    container_name: 'prometheus'
    volumes:
      - "./prometheus-config.yml:/etc/prometheus/prometheus.yml"
    networks:
      - spring-ai
    ports:
      - '9090:9090'
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317" # gRPC
      - "4318:4318" # HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - spring-ai

  grafana:
    image: 'grafana/grafana:latest'
    container_name: 'grafana'
    ports:
      - '3000:3000'
    volumes:
      - 'grafana-storage:/var/lib/grafana'
    networks:
      - spring-ai


  mysql:
    image: 'mysql:8.0'
    container_name: 'mysql'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spring_ai_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-ai

volumes:
  mysql-data:
  grafana-storage:

networks:
  spring-ai:
    driver: bridge
