spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:spring_ai_db}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update # Let JPA handle schema updates based on your entities

  lifecycle:
    timeout-per-shutdown-phase: 30s

  sql:
    init:
      mode: always

  docker:
    compose:
      enabled: false
      lifecycle-management: start_and_stop
      stop:
        command: down
      file: docker-compose.yml

  main:
    allow-bean-definition-overriding: true

  application:
    name: mcp-service

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-ada-002
      chat:
        options:
          model: gpt-4o
          temperature: 1
    vectorstore:
      qdrant:
        initialize-schema: true
        host: ${SPRING_AI_VECTORSTORE_QDRANT_HOST:localhost}
        port: ${SPRING_AI_VECTORSTORE_QDRANT_PORT:6334}
        collection-name: spring-ai-collection

    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
  level:
    org.springframework.ai.chat.client.advisor: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
